<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Subject;

class SubjectSeeder extends Seeder {
    public function run(): void {
        $subjects = [
            // --- GRADE 7 TO 10 ---
            '21st Century Literature from the Philippines and the World',
            'ARALING PANLIPUNAN',
            'Araling Panlipunan (Social Studies) 10',
            'Araling Panlipunan 7',
            'Araling Panlipunan 8',
            'Araling Panlipunan 9',
            'C.A.T.',
            'EDUKASYON SA PAGPAPAKATAO',
            'Edukasyon sa Pagpapakatao (EsP) 10',
            'Edukasyon sa Pagpapakatao (EsP) 7',
            'Edukasyon sa Pagpapakatao (EsP) 8',
            'Edukasyon sa Pagpapakatao (EsP) 9',
            'ENGLISH',
            'English 10',
            'English 7',
            'English 8',
            'English 9',
            'EPP/TLE 10 (Computer/Internet)',
            'EPP/TLE 7 (Computer/Internet)',
            'EPP/TLE 8 (Computer/Internet)',
            'EPP/TLE 9 (Computer/Internet)',
            'FILIPINO',
            'Filipino 10',
            'Filipino 7',
            'Filipino 8',
            'Filipino 9',
            'Foreign Language 10 (Mandarin)',
            'Foreign Language 7 (Mandarin)',
            'Foreign Language 8 (Mandarin)',
            'Foreign Language 9 (Mandarin)',
            'HOME ECONOMICS',
            'MAPEH 7',
            'MAPEH 8',
            'MAPEH 9',
            'MAPEH 10',
            'MATHEMATICS',
            'Mathematics 10',
            'Mathematics 7',
            'Mathematics 8',
            'Mathematics 9',
            'RELIGION 7',
            'Religion 8',
            'Religion 9',
            'Religion 10',
            'SCIENCE',
            'Science 10',
            'Science 7',
            'Science 8',
            'Science 9',
            'TLE',

            // --- SENIOR HIGH SCHOOL (SHS) ---
            'Applied Economics',
            'Basic Calculus',
            'Business Ethics and Social Responsibility',
            'Business Finance',
            'Business Math',
            'Communicty Engagement, Solidarity and Citizenship',
            'Computer Hardware Servicing 1',
            'Computer Hardware Servicing 2',
            'Computer Hardware Servicing 3',
            'Computer Hardware Servicing 4',
            'Computer Programming 1',
            'Computer Programming 2',
            'Computer Programming 3',
            'Computer Programming 4',
            'Contemporary Philippine Arts from the Region',
            'Creative Nonfiction',
            'Creative Writing',
            'Disciplines and Ideas in Applied Science',
            'Disciplines and Ideas in Social Sciences',
            'DRRM',
            'Earth and Life Science',
            'Empowerment Technologies: ICT for ABM',
            'English for Academic and Professional Purposes',
            'Entrepreneurship',
            'Fundamentals of Accountancy, Business and Management 1',
            'Fundamentals of Accountancy, Business and Management 2',
            'General Biology 1',
            'General Biology 2',
            'General Chemistry 1',
            'General Chemistry 2',
            'General Mathematics',
            'General Physics 1',
            'General Physics 2',
            'Introduction to the Philosophy of the Human Person',
            'Introduction to World Religions and Belief Systems',
            'Komunikasyon at Pannaliksik sa Wika at Kulturang Pilipino',
            'Media and Information Literacy',
            'Oral Communication',
            'Organization and Management',
            'Pagbasa at Pagsusuri ng Iba\'t ibang Teksto Tungo sa Pananaliksik',
            'Pagsulat sa Filipino sa Larangan ng Akademik',
            'Personal Development',
            'Philippine Politics and Governance',
            'Physical Education and Health 1',
            'Physical Education and Health 2',
            'Physical Education and Health 3',
            'Physical Education and Health 4',
            'Physical Science',
            'Practical Research 1',
            'Practical Research 2',
            'Pre Calculus',
            'Principles of Marketing',
            'Reading and Writing',
            'Research Project (Feasibility Study)',
            'Statistics and Probability',
            'Trends, Networks and Critical Thinking in the 21st Century Culture',
            'Understanding Culture, Society and Politics',
            'Work Immersion/Business Enterprise Simulation/Career Advocacy-ABM',
            'Work Immersion/Business Enterprise Simulation/Career Advocacy-HUMMS',
            'Work Immersion/Business Enterprise Simulation/Career Advocacy-STEM',
            'Work Immersion/Business Enterprise Simulation/Career Advocacy-TVL',
        ];

        foreach ($subjects as $sub) {
            Subject::create(['name' => $sub]);
        }
    }
}